feat: raise error if generation post>A x capacity
openclimatefix/india-api pull request #102
Opened 2024-12-26 06:24 UTC by suvanbanerjee

# Pull Request

## Description

Add HTTP 422 exception when trying to post data more than site_capacity_kw*capacity_factor

Fixes #87

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

2024-12-26 06:27 UTC, suvanbanerjee commented
@peterdudfield, I’ve made the changes to the India client. I believe I’ll need to do the same for dummydb, but in that case, the post function is just a placeholder. Also, could you guide me on how to test the changes? Are there any relevant docs available? I’m currently unable to test them.

2024-12-30 18:46 UTC, suvanbanerjee commented
@peterdudfield bumping this up

2025-01-02 09:11 UTC, peterdudfield commented
Hi @suvanbanerjee 

1. Yea dont worry about dummydb.
2. For testing, adding a test here would be great - https://github.com/openclimatefix/india-api/blob/main/src/india_api/internal/inputs/indiadb/test_indiadb.py#L102

2025-01-07 18:02 UTC, suvanbanerjee commented
@peterdudfield bumping this up

2025-01-07 22:08 UTC, peterdudfield commented on src/india_api/internal/inputs/indiadb/client.py
> +            capacity_factor = 1.1
could you just make this an enviornment variable, like this https://github.com/openclimatefix/pv-site-api/blob/main/pv_site_api/main.py#L288C19-L288C80

2025-01-07 22:08 UTC, peterdudfield requested changes
one small change, but otherwise looks good

2025-01-08 07:51 UTC, peterdudfield approved these changes
Thank you very much for this

2025-01-08 07:51 UTC, merged

2025-01-08 07:52 UTC, peterdudfield commented
@all-contributors please add @suvanbanerjee  for code